// This file is auto-generated by Lovable. Do not modify it.

export const lovable = {
  auth: {
    signInWithOAuth: async () => {
      throw new Error("OAuth is disabled in local mode.");
    },
  },
};
